### ISSUE TITLE
Import choices via json

### ISSUE THREAD

**Issue by timidak** [nxko/decidey#27]
## Feature request

What about adding a JSON import functionality to be able to add choices to the tool?
That would speed up our process and I would implement it, if it's a wanted feature. 

In my opinion the JSON should have a standard format. An array of strings would be the best, what do you think?

```json
["banana", "apple", "peach"] 
```

With this format it can be easily imported.

**Comment by nxko** [comment]
Good idea! 

About the icon: I thought of a round variant, in the same style as the other two buttons with white outlines.

Thanks!
